services:
  passbot:
    image: ghcr.io/shdrn2402/passbot:latest
    build: .
    container_name: pass-bot
    environment:
      - LOG_DIR=/logs
    volumes:
      - passbot_data:/app/data
      - passbot_logs:/logs
    env_file:
      - .env
    restart: unless-stopped

volumes:
  passbot_data:
  passbot_logs: